CREATE TABLE [dbo].[BranchDetails_P_Tbl] (
    [Cmp_Code]              INT           NOT NULL,
    [Br_RegionID]           BIGINT        NOT NULL,
    [Br_Code]               INT           NOT NULL,
    [Br_Name]               VARCHAR (50)  NOT NULL,
    [Br_ShortName]          VARCHAR (5)   NULL,
    [Br_Area]               VARCHAR (50)  NOT NULL,
    [Br_Address]            VARCHAR (100) NOT NULL,
    [Br_Phone1]             VARCHAR (50)  NOT NULL,
    [Br_ACode]              VARCHAR (15)  NOT NULL,
    [Br_FaxNo]              VARCHAR (15)  NOT NULL,
    [Br_Email]              VARCHAR (50)  NOT NULL,
    [Br_WeeklyOff]          CHAR (3)      NOT NULL,
    [Br_Sort]               INT           NOT NULL,
    [Br_AccCode]            BIGINT        NOT NULL,
    [Br_Online]             CHAR (1)      NOT NULL,
    [Br_OnlineDate]         DATETIME      NOT NULL,
    [Br_Status]             CHAR (1)      NOT NULL,
    [Br_ServerName]         VARCHAR (250) NOT NULL,
    [Br_IsProfitPoint]      CHAR (1)      NOT NULL,
    [Br_IsInventoryEnabled] CHAR (1)      NOT NULL,
    [Br_IsSalePoint]        CHAR (1)      NOT NULL,
    [Br_KSTNO]              VARCHAR (15)  NOT NULL,
    [Br_CSTNO]              VARCHAR (15)  NOT NULL,
    [Br_TIN]                VARCHAR (15)  NOT NULL,
    [Br_GSTIN]              VARCHAR (15)  NOT NULL,
    [Br_GSTPID]             VARCHAR (25)  NOT NULL
);

