CREATE TABLE [dbo].[LogDetails_T_Tbl] (
    [LD_LMID]       BIGINT        CONSTRAINT [DF_LogDetails_T_Tbl_LM_ID] DEFAULT ((0)) NOT NULL,
    [LD_FILELDNAME] VARCHAR (50)  CONSTRAINT [DF_LogDetails_T_Tbl_LD_FILELDNAME] DEFAULT ('') NOT NULL,
    [LD_FILELD]     VARCHAR (50)  CONSTRAINT [DF_LogDetails_T_Tbl_LD_FILELD] DEFAULT ('') NOT NULL,
    [LD_OLDVALUE]   VARCHAR (MAX) CONSTRAINT [DF_LogDetails_T_Tbl_LD_OLDVALUE] DEFAULT ('') NOT NULL,
    [LD_NEWVALUE]   VARCHAR (MAX) CONSTRAINT [DF_LogDetails_T_Tbl_LD_NEWVALUE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_LogDetails_T_Tbl] PRIMARY KEY CLUSTERED ([LD_LMID] ASC, [LD_FILELDNAME] ASC)
);

